//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public string emailChat { get; set; }
        public string mensajeChat { get; set; }
        public string respuestaChat { get; set; }
        public int idChat { get; set; }
    }
}
