//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public Nullable<int> fk_id_usuarioReg { get; set; }
        public Nullable<System.DateTime> fechaChat { get; set; }
        public string usuarioChat { get; set; }
        public string emailChat { get; set; }
        public string mensajeChat { get; set; }
        public string respuestaChat { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
