//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clima
    {
        public Nullable<int> fk_id_destino { get; set; }
        public Nullable<System.DateTime> fechaClima { get; set; }
        public Nullable<int> tempMax { get; set; }
        public Nullable<int> tempMin { get; set; }
        public string condicionClima { get; set; }
    
        public virtual Destino Destino { get; set; }
    }
}
