//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clima
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int TempMax { get; set; }
        public int TempMin { get; set; }
        public string Condicion { get; set; }
    }
}
