//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clima
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int TempMax { get; set; }
        public int TempMin { get; set; }
        public string Condicion { get; set; }
    }
}
