//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorArg.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Foro
    {
        public int id_topico { get; set; }
        public int fk_id_usuarioReg { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Contenido { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
