//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorArg.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExplorArgEntities : DbContext
    {
        public ExplorArgEntities()
            : base("name=ExplorArgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<Clima> Clima { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Atracciones> Atracciones { get; set; }
        public virtual DbSet<Destino> Destino { get; set; }
        public virtual DbSet<Foro> Foro { get; set; }
    }
}
