//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorArg.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExplorArgEntities : DbContext
    {
        public ExplorArgEntities()
            : base("name=ExplorArgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clima> Clima { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Atracciones> Atracciones { get; set; }
        public virtual DbSet<Destino> Destino { get; set; }
        public virtual DbSet<Foro> Foro { get; set; }
        public virtual DbSet<Chat> Chat { get; set; }
    }
}
